spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dooling
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true #JPQL 볼 수 있도록

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace